### ISSUE TITLE
i probably sounds stupid, but how do I install this? 

### ISSUE THREAD

**Issue by jogan-r** [arunkumar9t2/allistant#3]
im not a programmer, i just want this app, but i cant find an apk for it anywhere. it'd be real nice if someone could direct me to an apk, but if not thats okay, i just want to know how to install this.

**Comment by jessehickman** [comment]
https://github.com/arunkumar9t2/allistant/releases It's under the Releases tab.

**Comment by jogan-r** [comment]
yeah im not feeling too smart...
